In [3]:
from auxiliar.google_sheets import get_sheet_data,append_sheet_data

base_mood = get_sheet_data("mood_base")

In [4]:
base_mood

,data,incomodo,observacao,intensidade
0,05/03/2026,Dor na costela,Machuquei a costela esquerda no Jiu.,4
1,06/03/2026,Dor na costela,Não consegui dormir direito,3
2,07/03/2026,Dor na costela,Passou,2
3,05/03/2026,Cachorro do vizinho,Machuquei a costela esquerda no Jiu.,4
4,06/03/2026,Cachorro do vizinho,Não consegui dormir direito,3
5,07/03/2026,Cachorro do vizinho,Passou,2
6,07/03/2026,Dor na costela,Passou,2

In [2]:
from auxiliar.tratar_bases import pegar_moods_nao_resolvidos

pegar_moods_nao_resolvidos(base_mood)

              incomodo observacao intensidade
1  Cachorro do vizinho     Passou           2
2       Dor na costela     Passou           2